export const restaurants = [
    { name: "Heaven 23", description: "Stunning views and the famous King Size Shrimp Sandwich." },
    { name: "Thörnströms Kök", description: "Michelin-starred modern Swedish cuisine." },
    { name: "Sjömagasinet", description: "Waterfront restaurant specializing in seafood." },
    { name: "Koka", description: "Innovative Nordic cuisine with seasonal ingredients." },
    { name: "Toso", description: "Modern Asian fusion with a vibrant atmosphere." },
    { name: "Bhoga", description: "Scandinavian cuisine with a focus on local produce." },
    { name: "Gabriel Fisk- & Skaldjursbar", description: "Known for fresh oysters and fish dishes." },
    { name: "SK Mat & Människor", description: "Contemporary Swedish dishes with a Michelin star." },
    { name: "Somm Restaurant & Winebar", description: "Fine dining with an extensive wine selection." },
    { name: "Dorsia Hotel & Restaurant", description: "Elegant dining in a luxurious setting." },
    { name: "Avalon Restaurang", description: "Contemporary cuisine with a stylish ambiance." },
    { name: "Made in China", description: "Trendy Asian street food in a lively environment." },
    { name: "Kometen", description: "Traditional Swedish dishes in a historic setting." },
    { name: "Mr. P", description: "Casual dining with an international menu." },
    { name: "Brasa Churrascaria", description: "Brazilian-style steakhouse with all-you-can-eat meat." },
    { name: "Restaurang Atelier", description: "Creative dishes served in a rooftop setting." },
    { name: "Magazzino Ristorante Italiano", description: "Authentic Italian cuisine with a modern twist." },
    { name: "Ramen-Ya", description: "Cozy spot specializing in Japanese ramen dishes." },
    { name: "Familjen", description: "Contemporary Swedish dining in a warm, inviting atmosphere." },
    { name: "Levantine", description: "French-inspired cuisine with a focus on fresh, local ingredients." },
  ];